{
 "title": "Multi-tenant Allocator Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Request counts on Readers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "readersRequestsCounter_total" }
   ]
  },
  {
   "title": "Last Version Number Observed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "versionNumber" }
   ]
  },
  {
   "title": "Number of Requests processed by Issuer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "requestsCounter_total" }
   ]
  },
  {
   "title": "Size of Unallocated Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "unallocatedSpace" }
   ]
  },
  {
   "title": "Allocation Response Time on the Reader (microsec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum(rate(followerResponseTime_bucket[1m])) by (le))",
     "legendFormat": "75th percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(followerResponseTime_bucket[1m])) by (le))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(followerResponseTime_bucket[1m])) by (le))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(followerResponseTime_bucket[1m])) by (le))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(followerResponseTime_bucket[1m])) by (le))",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(followerResponseTime_bucket[1m])) by (le))",
     "legendFormat": "99.9th percentile"
    }
   ]
  },
  {
   "title": "Size of Fragmented Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "fragmentedSpace" }
   ]
  },
  {
   "title": "Allocation Algorithm Response Time on Issuer (microsec)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "requestProcessingGauge" }
   ]
  },
  {
   "title": "Number of Tenants Allocated on Issuer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "tenantNumberGauge" }
   ]
  }
 ]
}